# Generated by Django 5.1.7 on 2025-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_contato_alter_material_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
