# Generated by Django 5.1.7 on 2025-03-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='modulo',
            field=models.CharField(default='Módulo 1', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='ordem',
            field=models.IntegerField(default=1),
        ),
    ]
