# Generated by Django 5.1.7 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editar_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_video', models.FileField(upload_to='videos/original/')),
                ('edited_video', models.FileField(blank=True, null=True, upload_to='videos/edited/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
