# Generated by Django 5.1.7 on 2025-03-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_editar_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editar_Video',
        ),
    ]
