# Generated by Django 5.1.7 on 2025-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0008_delete_editar_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('OUTROS', 'Outros Tipos')], default='PDF', max_length=10),
        ),
    ]
