# Generated by Django 5.1.7 on 2025-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0011_alter_profile_options_profile_progresso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='aulas_assistidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progresso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
