# Generated by Django 5.1.7 on 2025-03-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0012_alter_profile_options_profile_aulas_assistidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aulas_assistidas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progresso',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ultimo_acesso',
        ),
        migrations.AlterField(
            model_name='profile',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='language.profile'),
        ),
    ]
