# Generated by Django 5.1.7 on 2025-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0014_teacher_student_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aulas_assistidas',
            field=models.IntegerField(default=0),
        ),
    ]
