# Generated by Django 5.1.7 on 2025-03-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0015_student_aulas_assistidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='aulas_assistidas',
        ),
    ]
